# ----------- CONFIGURABLE START -----------
title:            "Godot 10pos"
description:      "Coding challenge"
url:              https://www.gammagames.net/godot-10pow # Site url, without a slash at the end.
signoff:          "Jesse" # Your name
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         Posts
    url:          /
    external:     false
  - name:         About me
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"
